# Generated by Django 5.2.3 on 2025-06-17 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(unique=True, verbose_name='ID Города')),
                ('city_name', models.CharField(max_length=100, verbose_name='Название города')),
                ('avg_price_sqm', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Средняя цена за м²')),
                ('price_change_percent', models.CharField(help_text="Например, '+1.2%' или '-0.5%'", max_length=10, verbose_name='Изменение цены (строка)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Аналитика по городу (витрина)',
                'verbose_name_plural': 'Аналитика по городам (витрина)',
                'ordering': ['city_id'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название района')),
                ('geometry', models.JSONField(verbose_name='Геометрия (GeoJSON)')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('city_id', models.IntegerField(verbose_name='ID Города')),
                ('property_type', models.CharField(choices=[('new', 'Новостройка'), ('secondary', 'Вторичное жилье')], max_length=30, verbose_name='Тип недвижимости')),
                ('property_class', models.CharField(choices=[('economy', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес'), ('premium', 'Премиум'), ('mass', 'Новая массовая'), ('quality', 'Новая качественная'), ('old', 'Старый Фонд')], max_length=30, verbose_name='Класс недвижимости')),
                ('avg_price_sqm', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Средняя цена за м²')),
                ('year', models.IntegerField(editable=False, verbose_name='Год')),
                ('quarter', models.IntegerField(editable=False, verbose_name='Квартал')),
                ('month', models.IntegerField(editable=False, verbose_name='Месяц')),
            ],
            options={
                'verbose_name': 'Точка аналитических данных',
                'verbose_name_plural': 'Точки аналитических данных',
                'ordering': ['-date'],
                'unique_together': {('date', 'city_id', 'property_type', 'property_class')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=10, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('avg_price_sqm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Средняя цена за м²')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='realty_analytics.district', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'История цены',
                'verbose_name_plural': 'История цен',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_expires_on', models.DateField(blank=True, null=True, verbose_name='Подписка активна до')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
