# Generated by Django 5.2.3 on 2025-06-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name'], 'verbose_name': 'Территория (район)', 'verbose_name_plural': 'Территории (районы)'},
        ),
        migrations.AddField(
            model_name='district',
            name='ao_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID АО (адм. округа)'),
        ),
        migrations.AddField(
            model_name='district',
            name='city_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID Города'),
        ),
        migrations.AddField(
            model_name='district',
            name='raion_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID Района'),
        ),
        migrations.AddField(
            model_name='district',
            name='region_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID Региона'),
        ),
        migrations.AddField(
            model_name='district',
            name='smart_name',
            field=models.CharField(blank=True, help_text="Например, 'ЦАО, Арбат'", max_length=255, verbose_name='Короткое/умное название'),
        ),
        migrations.AddField(
            model_name='district',
            name='zonen_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID Зоны (территории)'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Официальное/полное название'),
        ),
    ]
