# Generated by Django 5.2.3 on 2025-06-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty_analytics', '0002_alter_district_options_district_ao_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL (слаг)'),
        ),
        migrations.AddField(
            model_name='district',
            name='slug',
            field=models.SlugField(default=1, help_text="Уникальный URL-идентификатор. Заполняется латиницей, например, 'tsao-khamovniki'", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
