# Generated by Django 5.2.3 on 2025-06-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty_analytics', '0003_article_slug_district_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsdatapoint',
            name='property_class',
            field=models.CharField(choices=[('economy', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес'), ('premium', 'Премиум'), ('vall', 'Вторичная'), ('pall', 'Строящаяся'), ('mass', 'Новая массовая'), ('quality', 'Новая качественная'), ('elite', 'Новая премиум'), ('oldfund', 'Старый Фонд'), ('stal', 'Сталинки'), ('sovet', 'Советское массовое')], max_length=30, verbose_name='Класс недвижимости'),
        ),
        migrations.CreateModel(
            name='ZoneAnalyticsDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата точки данных')),
                ('zonen_id', models.IntegerField(db_index=True, verbose_name='ID Зоны/Территории')),
                ('property_type', models.CharField(choices=[('new', 'Новостройка'), ('secondary', 'Вторичное жилье')], max_length=20, verbose_name='Тип недвижимости')),
                ('property_class', models.CharField(choices=[('economy', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес'), ('premium', 'Премиум'), ('vall', 'Вторичная'), ('pall', 'Строящаяся'), ('mass', 'Новая массовая'), ('quality', 'Новая качественная'), ('elite', 'Новая премиум'), ('oldfund', 'Старый Фонд'), ('stal', 'Сталинки'), ('sovet', 'Советское массовое')], max_length=20, verbose_name='Класс недвижимости')),
                ('avg_price_sqm', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Средняя цена за м²')),
                ('year', models.IntegerField(editable=False, verbose_name='Год')),
                ('quarter', models.IntegerField(editable=False, verbose_name='Квартал')),
                ('month', models.IntegerField(editable=False, verbose_name='Месяц')),
            ],
            options={
                'verbose_name': 'Точка данных по зоне',
                'verbose_name_plural': 'Точки данных по зонам',
                'ordering': ['-date'],
                'unique_together': {('date', 'zonen_id', 'property_type', 'property_class')},
            },
        ),
    ]
