# Generated by Django 5.2.3 on 2025-06-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty_analytics', '0004_alter_analyticsdatapoint_property_class_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zoneanalyticsdatapoint',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='zoneanalyticsdatapoint',
            name='city_id',
            field=models.IntegerField(db_index=True, default=77, verbose_name='ID Города'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='zoneanalyticsdatapoint',
            unique_together={('date', 'city_id', 'zonen_id', 'property_type', 'property_class')},
        ),
    ]
